// <auto-generated />
using System;
using Live_poll.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Live_poll.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261006091540_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Live_poll.Data.Participant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("nickname");

                    b.Property<int?>("OptionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("option_id");

                    b.Property<int>("PollId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("poll_id");

                    b.HasKey("Id");

                    b.HasIndex("OptionId");

                    b.HasIndex("PollId", "Nickname")
                        .IsUnique();

                    b.ToTable("participants", (string)null);
                });

            modelBuilder.Entity("Live_poll.Data.Poll", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("closed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("question");

                    b.Property<string>("SessionKey")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("TEXT")
                        .HasColumnName("session_key");

                    b.HasKey("Id");

                    b.HasIndex("SessionKey")
                        .IsUnique();

                    b.ToTable("polls", (string)null);
                });

            modelBuilder.Entity("Live_poll.Data.PollOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("PollId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("poll_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("text");

                    b.HasKey("Id");

                    b.HasIndex("PollId");

                    b.ToTable("options", (string)null);
                });

            modelBuilder.Entity("Live_poll.Data.Participant", b =>
                {
                    b.HasOne("Live_poll.Data.PollOption", "Option")
                        .WithMany("Participants")
                        .HasForeignKey("OptionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Live_poll.Data.Poll", "Poll")
                        .WithMany("Participants")
                        .HasForeignKey("PollId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Option");

                    b.Navigation("Poll");
                });

            modelBuilder.Entity("Live_poll.Data.PollOption", b =>
                {
                    b.HasOne("Live_poll.Data.Poll", "Poll")
                        .WithMany("Options")
                        .HasForeignKey("PollId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Poll");
                });

            modelBuilder.Entity("Live_poll.Data.Poll", b =>
                {
                    b.Navigation("Options");

                    b.Navigation("Participants");
                });

            modelBuilder.Entity("Live_poll.Data.PollOption", b =>
                {
                    b.Navigation("Participants");
                });
#pragma warning restore 612, 618
        }
    }
}
